INFO:pyaf.timing:('OPERATION_START', ('SIGNAL_TRAINING', {'Signals': ['AirPassengers'], 'Transformations': [('AirPassengers', 'None', '_', 'T+S+R'), ('AirPassengers', 'None', 'Diff_', 'T+S+R'), ('AirPassengers', 'None', 'RelDiff_', 'T+S+R'), ('AirPassengers', 'None', 'CumSum_', 'T+S+R')], 'Cores': 4}))
INFO:pyaf.timing:('OPERATION_START', ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': '_AirPassengers'}))
INFO:pyaf.timing:('OPERATION_START', ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': 'Diff_AirPassengers'}))
INFO:pyaf.timing:('OPERATION_START', ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': 'CumSum_AirPassengers'}))
INFO:pyaf.timing:('OPERATION_START', ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': 'RelDiff_AirPassengers'}))
/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
INFO:pyaf.timing:('OPERATION_END_ELAPSED', 0.293, ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': 'CumSum_AirPassengers'}))
INFO:pyaf.timing:('OPERATION_END_ELAPSED', 0.298, ('TRAINING', {'Signal': 'AirPassengers', 'Transformation': '_AirPassengers'}))
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 380, in run_transform_thread
    arg.mSigDec.train(arg.mInputDS, arg.mSplit, arg.mTime, arg.mSignal, arg.mHorizon, arg.mTransformation, arg.mDecompositionType);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 194, in train
    lAREstimator.estimate();
  File "/home/circleci/project/pyaf/TS/SignalDecomposition_AR.py", line 323, in estimate
    self.add_model_if_activated(cycle_residue, 'CROSTON', interm.cCroston_Model, lLags, False)
  File "/home/circleci/project/pyaf/TS/SignalDecomposition_AR.py", line 278, in add_model_if_activated
    if(self.mOptions.mActiveAutoRegressions[model_type_str + 'X'] and (self.mExogenousInfo is not None)):
KeyError: 'CROSTONX'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/project/pyaf/ForecastEngine.py", line 25, in train
    self.mSignalDecomposition.train(iInputDS, iTime, iSignal, iHorizon, iExogenousData);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 666, in train
    lTrainer.train(iInputDS, lSplits , self.mDateColumns, self.mSignals, self.mHorizons)
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 416, in train
    self.train_all_transformations(iInputDS, iSplits, iTime, iSignals, iHorizon);
  File "/home/circleci/project/pyaf/TS/SignalDecomposition.py", line 505, in train_all_transformations
    for res in pool.imap(run_transform_thread, args):
  File "/home/circleci/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
KeyError: 'CROSTONX'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/tests/missing_data/test_missing_data_air_passengers_Interpolate_Constant.py", line 3, in <module>
    gen.test_air_passengers_missing_data('Interpolate', 'Constant')
  File "/home/circleci/project/tests/missing_data/test_missing_data_air_passengers_generic.py", line 34, in test_air_passengers_missing_data
    lEngine.train(df , b1.mTimeVar , b1.mSignalVar, H);
  File "/home/circleci/project/pyaf/ForecastEngine.py", line 30, in train
    raise tsutil.PyAF_Error("TRAIN_FAILED");
pyaf.TS.Utils.PyAF_Error: TRAIN_FAILED
Exception ignored in: <function cTimer.__del__ at 0x7fe1f895c700>
Traceback (most recent call last):
  File "/home/circleci/project/pyaf/TS/Utils.py", line 89, in __del__
  File "/home/circleci/project/pyaf/TS/Utils.py", line 65, in get_pyaf_timing_logger
ImportError: sys.meta_path is None, Python is likely shutting down
